Fix Month parser
BadChoice/reporter pull request #1
Opened 2017-09-01 15:54 UTC by PauBenetPrat

Always carbon::parse regarding its string or Cabron date
ExcepTypes renamed to ExceptTypes

2017-09-01 16:00 UTC, BadChoice requested changes

2017-09-01 16:00 UTC, BadChoice commented on src/DataTransformers/Transformers/Date.php
> +        return substr(timeZoned(Carbon::parse($value)),0,10);
fes-lo com els altres i utiliza el auth()->user()->timezone, el que en comptes del timezoned,
de totes maneres com que és un paquet, i potser que el user() no tingui timezone, hauriem de fer el isset abans de posar-li

2017-09-01 16:00 UTC, BadChoice commented on src/DataTransformers/Transformers/Date.php
> +        return substr(timeZoned(Carbon::parse($value)),0,10);
i faria el toDateString() de carbon en comptes del substr

2017-09-01 16:56 UTC, PauBenetPrat commented
Amb el timezone null ja he comprobat i no peta.

2017-09-03 14:08 UTC, BadChoice approved these changes

2017-09-03 14:08 UTC, merged