Add global final filter
BadChoice/reporter pull request #104
Opened 2021-01-28 12:23 UTC by PauBenetPrat

2021-01-29 09:29 UTC, BadChoice requested changes

2021-01-29 09:29 UTC, BadChoice commented on src/Filters/QueryFilters.php
> +        if (method_exists($this, 'globalFinalFilter')) {
que es aixo????

2021-01-29 09:42 UTC, PauBenetPrat commented on src/Filters/QueryFilters.php
> +        if (method_exists($this, 'globalFinalFilter')) {
Tinc el problema aquell de l'addSelect amb els superGroups, que fem al globalFIlter i després sobreescrivim amb un select al OrderContentFilters. La idea es afegir un mètode, que enlloc de cridar-se al principi (com el globalFilter) es cridi al final. Així podrem posar els addSelects que volguem sense que es sobreescriguin.

2021-02-05 11:31 UTC, BadChoice approved these changes

2021-02-05 11:32 UTC, merged