get export headers and body for chain masters reports
BadChoice/reporter pull request #80
Opened 2019-02-19 14:57 UTC by PauBenetPrat

2019-02-20 12:30 UTC, BadChoice requested changes

2019-02-20 12:30 UTC, BadChoice commented on src/Report.php
> +        return explode("\n", app($this->reportExporter)->toCsv($this->query())->getOutput())[0] . "\n";
i esu? com es que m'ho poses al Report?

2019-02-25 09:13 UTC, PauBenetPrat commented on src/Report.php
> +        return explode("\n", app($this->reportExporter)->toCsv($this->query())->getOutput())[0] . "\n";
Ja ho he tret

2019-02-25 10:37 UTC, BadChoice approved these changes

2019-02-25 10:37 UTC, merged