remove tags keeped on session
BadChoice/reporter pull request #88
Opened 2019-10-23 09:37 UTC by PauBenetPrat

2019-10-30 15:22 UTC, BadChoice requested changes

2019-10-30 15:22 UTC, BadChoice commented on src/Filters/Filters.php
> -        "tag"
perque no els volem els tags?

2019-10-30 16:09 UTC, PauBenetPrat commented on src/Filters/Filters.php
> -        "tag"
Es queden a la sessió, però no es carreguen als filtres i no funciona bé. Molaria poder-los mantenir bé, però dona més problemes que ajudes

2019-11-19 15:22 UTC, BadChoice approved these changes

2019-11-19 15:22 UTC, merged