New transformers added for grouped Invoices
BadChoice/reporter pull request #9
Opened 2017-09-18 14:33 UTC by PauBenetPrat

2017-09-18 14:51 UTC, BadChoice requested changes

2017-09-18 14:51 UTC, BadChoice commented on src/DataTransformers/Transformers/LinkContent.php
> +
No hi ha un link transform ja?

2017-09-18 14:51 UTC, BadChoice commented on src/DataTransformers/Transformers/TransFunction.php
> +
No hi ha un callback ja?

2017-09-18 14:59 UTC, PauBenetPrat commented on src/DataTransformers/Transformers/LinkContent.php
> +
He adaptat el Link.php per poder eliminar el LinkContent

2017-09-18 15:00 UTC, PauBenetPrat commented on src/DataTransformers/Transformers/TransFunction.php
> +
El callback funciona diferent. He modificar el fitxer perquè el puguis veure a la PR

2017-09-20 15:40 UTC, PauBenetPrat commented
@BadChoice al final no m'has acceptat això....

2017-09-20 15:45 UTC, BadChoice commented
Diu que "requested changes" ?

2017-09-21 07:52 UTC, PauBenetPrat commented
Si, perquè m'has dit 

> No hi ha un callback ja?
i jo:

> El callback funciona diferent

2017-09-21 08:00 UTC, BadChoice commented
Ok desprs quan acabi de l'edu vensi ho mirem,v ull veure el vell que funciona diferent abans

2017-09-23 14:46 UTC, BadChoice requested changes
El revisem dilluns aquest, diria ques una mica dificil d'entndre aquesta funcio hehe

2017-09-26 08:59 UTC, PauBenetPrat commented on src/DataTransformers/Transformers/TransFunction.php
> +
CallObjectMethod

2017-09-26 10:51 UTC, BadChoice approved these changes

2017-09-26 10:51 UTC, merged